import { NextResponse } from "next/server";
import { verifyAdmin } from "@/lib/admin-auth.server";
import { createClient as createSupabaseAdmin } from "@supabase/supabase-js";

export async function POST(request: Request) {
  const result = await verifyAdmin(request);
  if (!result.authorized) return result.response;

  try {
    const supabase = createSupabaseAdmin(
      process.env.NEXT_PUBLIC_SUPABASE_URL || "",
      process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || ""
    );

    const { error } = await supabase.from("admin_notifications").insert({
      type: "info",
      title: "Test Notification",
      message: "This is a test notification generated by the admin dashboard.",
      read: false
    });

    if (error) {
      console.error("Test notification DB error:", error);
      return NextResponse.json({ error: "Failed to push notification to database" }, { status: 500 });
    }

    return NextResponse.json({ success: true, message: "Test notification system is working." });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
